version: "3"

services:
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - mongo
        volumes:
            - ./server:/usr/src/app
            - '/app/node_modules'
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        depends_on:
            - server
        stdin_open: true
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - 27017:27017