version: "3"

services:
    server:
        build: ./server
        ports:
        - 8080:8080
        depends_on:
        - mongo
        volumes:
            - ./server:/usr/src/app
    mongo:
        image: mongo
        ports:
        - 27017:27017